name: EC2 Start, Stop and Terminate

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select action"
        required: true
        type: choice
        options:
          - start
          - stop
          - terminate

jobs:
  ec2-control:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Start EC2
        if: ${{ inputs.action == 'start' }}
        run: |
          echo "Starting EC2..."
          aws ec2 start-instances \
            --instance-ids i-0ed018af10cfa4aa5 \
            --region ap-southeast-1
          echo "Instance Started"

      - name: Stop EC2
        if: ${{ inputs.action == 'stop' }}
        run: |
          echo "Stopping EC2..."
          aws ec2 stop-instances \
            --instance-ids i-0ed018af10cfa4aa5 \
            --region ap-southeast-1
          echo "Instance Stopped"

      - name: Terminate EC2
        if: ${{ inputs.action == 'terminate' }}
        run: |
          echo "Terminating EC2..."
          aws ec2 terminate-instances \
            --instance-ids i-0ed018af10cfa4aa5 \
            --region ap-southeast-1
          echo "Instance Terminated"
